<?php

/**
 * Implementation of hook_help().
 */
function system_settings_service_help($section) {
  switch ($section) {
    case 'admin/help#services_system_settings':
      return t('<p>Provides system settings services. Requires services.module.</p>');
    case 'admin/modules#description':
      return t('Provides system settings services. Requires services.module.');
  }
}

/**
 * Implementation of hook_service()
 */
function system_settings_service_service() {
  return array(
    
    // content_copy.import
    array(
      '#method'   => 'system_settings.import',
      '#callback' => 'system_settings_service_import',
      '#args'     => array(
        array(
          '#name'         => 'settings',
          '#type'         => 'struct',
          '#description'  => t('Array of system settings form values.'),
        ),
      ),
      '#return'   => 'string',
      '#help'     => t('Import system settings')
    ),
  );
}

function system_settings_service_import($form_values) {
  $form_id = $form_values['form_id'];
  system_settings_form_submit($form_id, $form_values);
  watchdog("Services", "System Settings Import Service run for $form_id.");
  return "$form_id imported";
}
